// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtplIbXUrER47Yii7gYea3v2VJY3KXE2Q',
    appId: '1:1039704902784:web:859f4e4609362fac8f6a65',
    messagingSenderId: '1039704902784',
    projectId: 'optima-5d878',
    authDomain: 'optima-5d878.firebaseapp.com',
    storageBucket: 'optima-5d878.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8le1IsLySpcbFVQ5rLBJ_OGZhX2_wAkU',
    appId: '1:1039704902784:android:5a79371c0f15682a8f6a65',
    messagingSenderId: '1039704902784',
    projectId: 'optima-5d878',
    storageBucket: 'optima-5d878.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaMOPf3XD348qiub_977NDQ16EcSFsrzw',
    appId: '1:1039704902784:ios:f9cc93cd2d9a87cf8f6a65',
    messagingSenderId: '1039704902784',
    projectId: 'optima-5d878',
    storageBucket: 'optima-5d878.firebasestorage.app',
    iosBundleId: 'com.vilamuzz.optima',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaMOPf3XD348qiub_977NDQ16EcSFsrzw',
    appId: '1:1039704902784:ios:f9cc93cd2d9a87cf8f6a65',
    messagingSenderId: '1039704902784',
    projectId: 'optima-5d878',
    storageBucket: 'optima-5d878.firebasestorage.app',
    iosBundleId: 'com.vilamuzz.optima',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtplIbXUrER47Yii7gYea3v2VJY3KXE2Q',
    appId: '1:1039704902784:web:6b28e92157f442938f6a65',
    messagingSenderId: '1039704902784',
    projectId: 'optima-5d878',
    authDomain: 'optima-5d878.firebaseapp.com',
    storageBucket: 'optima-5d878.firebasestorage.app',
  );
}
